### ISSUE TITLE
GL_FRAGMENT_SHADER shader failed to compile

### ISSUE THREAD

**Issue by mileshiroo** [kylemcdonald/ofxBlur#1]
Hi Kyle, 

I loaded the example, and get these errors when I try to compile:

```
[ error ] ofShader: setupShaderFromSource(): GL_FRAGMENT_SHADER shader failed to compile
[ error ] ofShader: GL_FRAGMENT_SHADER shader reports:
ERROR: 0:1: '' :  #version required and missing.
[ error ] ofShader: linkProgram(): trying to link GLSL program, but no shaders created yet
```

I'm using ofSketch 0.4, and running OS X 10.10. Let me know if I can provide more information. 

Miles

**Comment by kylemcdonald** [comment]
interesting! what if you add, between line 51 and 52 here https://github.com/kylemcdonald/ofxBlur/blob/master/src/ofxBlur.cpp#L51-L52

``` c++
src << "#version 120\n";
```
