### ISSUE TITLE
regex_error when setting up fragment shader

### ISSUE THREAD

**Issue by frauzufall** [kylemcdonald/ofxBlur#3]
Hey,

I get a `regex_error` at this line on Ubuntu 14.10 64bit:

```
blurShader.setupShaderFromSource(GL_FRAGMENT_SHADER, blurSource);
```

Thank you for any help! What can I do to get more information about this error?
Deborah

**Comment by frauzufall** [comment]
This is the complete error message:

```
[verbose] ofShader: checkAndCreateProgram(): creating GLSL program
terminate called after throwing an instance of 'std::regex_error'
  what():  regex_error
[verbose] ofSignalHandler: Aborted
Aborted (core dumped)
```

**Comment by frauzufall** [comment]
I updated to Ubuntu 15.04 and now it doesn't crash anymore.

**Comment by kylemcdonald** [comment]
wow, really baffled as to why upgrading would fix something like this, but glad to know you found a solution!
