### ISSUE TITLE
shader conflicts?

### ISSUE THREAD

**Issue by digitalcoleman** [kylemcdonald/ofxBlur#6]
I suspect there is a conflict with using this plus the newer ofGLWindow renderer? My main.cpp is 

```
    ofGLWindowSettings settings;
    settings.setGLVersion(3,2);
    ofCreateWindow(settings);
    ofSetWindowShape(1920, 1080);
```

This is what I get as an error:
[ error ] ofShader: setupShaderFromSource(): GL_FRAGMENT_SHADER shader failed to compile
[ error ] ofShader: GL_FRAGMENT_SHADER shader reports:
ERROR: 0:1: '' :  version '120' is not supported
ERROR: 0:2: '' :  #version required and missing.
WARNING: 0:2: extension 'GL_ARB_texture_rectangle' is not supported

[ error ] ofShader: GL_FRAGMENT_SHADER, offending line 1 :
        1   #version 120
        2   #extension GL_ARB_texture_rectangle : enable
        3   uniform sampler2DRect source;

[ error ] ofShader: checkProgramLinkStatus(): program failed to link
[ error ] ofShader: ofShader: program reports:
ERROR: One or more attached shaders not successfully compiled

[ error ] ofShader: setupShaderFromSource(): GL_FRAGMENT_SHADER shader failed to compile
[ error ] ofShader: GL_FRAGMENT_SHADER shader reports:
ERROR: 0:1: '' :  version '120' is not supported
ERROR: 0:2: '' :  #version required and missing.
WARNING: 0:2: extension 'GL_ARB_texture_rectangle' is not supported

[ error ] ofShader: GL_FRAGMENT_SHADER, offending line 1 :
        1   #version 120
        2   #extension GL_ARB_texture_rectangle : enable
        3   uniform sampler2DRect s0,s1,s2,s3,s4;

[ error ] ofShader: checkProgramLinkStatus(): program failed to link
[ error ] ofShader: ofShader: program reports:
ERROR: One or more attached shaders not successfully compiled"

**Comment by digitalcoleman** [comment]
FWIW, I found a working branch for the programmable renderer here: https://github.com/robotconscience/ofxBlur

**Comment by kylemcdonald** [comment]
very old issue but just wanted to say thanks for the note, i incorporated the changes from @robotconscience and also fixed a bug where everything was flipped on the y axis.
